### ISSUE TITLE
RimPoint Wishlist / TODOs

### ISSUE THREAD

**Issue by unit0016** [effigy-se/effigy-se#426]
As you've heard about if you've been monitoring the mapping channel, I've been working on a second map post-foxhole set in a jungle setting. While I'm admittedly *hesitant* to go through with it considering the sheer scale, some of the code has already been mistakenly committed to master (which wasn't actually my fault, if you can beleive!)

You can keep up with development [here](https://github.com/unit0016/effigy-se/tree/RimPoint), and see the PR here: #428 

# TODO:
- [x] Security
- [x] Cargo
- [x] Command
- [x] AI Sat
- [x] Tool Storage
- [x] Vacant Commissary
- [x] Holodeck / Fitness
- [x] Aux Base
- [x] Gateway
- [x] Solar Panels
- [x] Radshelters
- [x] Escape Pods
- [x] Arrivals Shuttle
- [x] Lighting Pass
- [x] AtmosDiff Pass
- [x] APC Pass
- [x] Air Alarm Pass
- [x] Fire Alarm Pass
- [x] Extinguisher Pass
- [x] Fix easter egg cookie description
- [x] Intercom Pass
- [x] External Lighting
- [x] Escape Shuttle
- [x] Ferry Dock
- [x] Camera Pass
- [x] dorm 4 shutters
- [x] Bot Beacons
- [x] Flora Pass

# WISHLIST:
- [ ] Day / Night Cycle
- [x] Some way to do fucking... .g.. .disposals.. gughghu
- [ ] Add Rain, Re-add Acid Rain
- [x] Jungle Ruins (ENABLE CEILINGS.)
- [x] Hem up the dorms' overarcing bit a bit more, maybe??
